apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: webgo
images:
- name: webgo
  newName: paulofponciano/webgo
  newTag: 7130ebd14ed58f624026ba820448d6ee7d3d7760
